name: Calculator checks

on:
  push:
    paths:
      - "calculator/**"
      - ".github/workflows/calculator*.yml"
  pull_request:
    paths:
      - "calculator/**"
      - ".github/workflows/calculator*.yml"

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: calculator

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: make install

      - name: Check
        run: make check
